name = "syncstuff-web"
compatibility_date = "2024-01-01"
main = "./server.ts"

[vars]
GITHUB_OAUTH_CLIENT_ID = "Ov23li5ZRzCQoPWMN21O"
GITHUB_OAUTH_CALLBACK = "https://syncstuff-web.involvex.workers.dev/auth/callback"
GITHUB_OAUTH_CLIENT_SECRET = "07631a180f65b26a290791b111dd1ba01dae370b"
DISCORD_CLIENT_ID = "1458236674097283236"
DISCORD_OAUTH_CALLBACK = "https://syncstuff-web.involvex.workers.dev/auth/callback"
SESSION_SECRET = "dev-session-secret"
API_URL = "https://syncstuff-api.involvex.workers.dev"

[assets]
directory = "./build/client"
binding = "ASSETS"

[[d1_databases]]
binding = "syncstuff_db"
database_name = "syncstuff-db"
database_id = "94e9ef8c-2032-4ee5-9a97-b6280eab0957"