name = "syncstuff-web"
compatibility_date = "2024-01-01"
main = "./server.ts"

[assets]
directory = "./build/client"
binding = "ASSETS"

[[d1_databases]]
binding = "syncstuff_db"
database_name = "syncstuff-db"
database_id = "94e9ef8c-2032-4ee5-9a97-b6280eab0957"